config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  get   'users/:id'   =>  'users#show'
  resources :items do
    collection do
      post ':id/purchase' => 'items#purchase'
      get 'saled' => 'items#saled'
      get 'bought' => 'items#bought'
    end
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :saler, class_name: "User"
  belongs_to :buyer, class_name: "User"
  has_many :comments

  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :state, presence: true
  validates :postage, presence: true
  validates :region, presence: true
  validates :shipping_date, presence: true
  validates :price, presence: true

  include FriendlyId
  friendly_id :random
  before_create do
    self.random = SecureRandom.hex(10)
  end

  def sold?
    buyer.present?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, -> { where("buyer_id is NULL") }, foreign_key: "saler_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "saler_id", class_name: "Item"
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:new, :show, :purchase, :edit]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], item_id: comment_params[:item_id], user_id: current_user.id)
    reload_comments
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(item_id: params[:item_id])
  end

  def reload_comments
    @item = Item.friendly.find(params[:item_id])
    redirect_to "/items/#{@item.random}"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :purchase, :edit, :destroy, :update]
  before_action :set_all_items, only: [:index, :saled, :bought]

  def index
    @items = @items.where(release: "全体公開")
  end

  def saled
    @items = @items.where(saler_id: current_user.id)
  end

  def bought
    @items = @items.where(buyer_id: current_user.id)
  end

  def show
    @user = User.find(@item.saler_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(name: item_params[:name], image: item_params[:image], description: item_params[:description], category: item_params[:category], state: item_params[:state], postage: item_params[:postage], region: item_params[:region], shipping_date: item_params[:shipping_date], price: item_params[:price], release: item_params[:release], saler_id: current_user.id)
    if @item.save
      redirect_to "/items", notice: "商品を投稿しました"
    else
      flash.now[:alert] = "必須項目が入力されているかもう一度確認してください。"
      render 'new'
    end
  end

  def purchase
    Payjp.api_key = Rails.application.secrets.payjp_secret_key
    Payjp::Charge.create(
      :amount => @item.price,
      :card => params['payjp-token'],
      :currency => 'jpy'
    )
    @item.buyer_id = current_user.id
    @item.save
    saler = User.find(@item.saler_id)
    saler.wallet += @item.price * 0.9
    saler.save
  end

  def destroy
    @item.destroy if @item.saler_id == current_user.id
  end

  def edit
    @item.image.cache! if @item.image.present?
  end

  def update
    if @item.saler_id == current_user.id
      @item.update(name: item_params[:name], image: item_params[:image], description: item_params[:description], category: item_params[:category], state: item_params[:state], postage: item_params[:postage], region: item_params[:region], shipping_date: item_params[:shipping_date], price: item_params[:price], release: item_params[:release],image_cache: item_params[:image_cache], saler_id: current_user.id)
    end
  end


  private
  def item_params
    params.require(:item).permit(:name, :image, :description, :category, :state, :postage, :region, :shipping_date, :price, :release, :image_cache)
  end

  def set_item
    @item = Item.friendly.find(params[:id])
  end

  def set_all_items
    @items = Item.all.order("created_at DESC")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_comment.html.haml
%li
  .icon-and-name
    .user-icon
      = image_tag("comments/user-icon.svg")
    .user-name
      = comment.user.nickname
  .user-comment
    = simple_format(comment.text)

app/views/items/_header.html.haml
.default-container
  %header
    .logo-and-search.clearfix
      =link_to root_path do
        = image_tag("header/logo.svg", class: "logo-and-search__logo left-float")
      .search
        %form.logo-and-search__search.right-float
          %input{value:"", placeholder:"キーワードから探す" }
          %i.fa.fa-search
    .lists.clearfix
      .lists__left.left-float
        %ul
          %li.categories
            %h2
              = link_to "" do
                カテゴリー
          %li.brands
            %h2
              = link_to "" do
                ブランド
      .signin-and-signup.right-float
        %ul.account
          - if user_signed_in?
            %li.signin-btn
              = link_to "マイページ", "/users/#{current_user.id}", class: "signin-btn__text"
          - else
            %li.signin-btn
              = link_to "ログイン", user_session_path, class: "signin-btn__text"
            %li.signup-btn
              = link_to "新規会員登録", user_session_path, class: "signup-btn__text"
          %end

app/views/items/_item.html.haml
= link_to item_path(item), "data-turbolinks": false do
  .items-box
    .detail-page
      = image_tag item.image, class: "detail-page__img"
      - if item.sold?
        .item-sold-out-badge-mini
          SOLD
      %end
      .detail-page__body
        %h3.item-name
          = item.name
        .item-price
          ¥
          = item.price.to_s(:delimited)

app/views/items/_items.html.haml
= link_to item_path(item.id) do
  .items-box
    .detail-page
      = image_tag item.image, class: "detail-page__img"
      / = image_tag("pickup-contents/item1.jpg", class: "detail-page__img")
      .detail-page__body
        %h3.item-name
          = item.name
        .item-price
          ¥
          = item.price

app/views/items/bought.html.haml
.header-wrapper
= render "items/main/header"

.items
.pickup-contents-wrapper
.pickup-contents
  %h2.pickup-contents__title
    %p 購入した商品一覧 </br></br>
  %section.items-contents
    .items-box-content
      = render partial: 'item', collection: @items, as: :item

.bottom-dl-area-wrapper
= render "items/main/bottom-dl-area"
.fotter-wrapper
= render "items/main/fotter"

app/views/items/destroy.html.haml
.single-container
  .single-header
    %h1
    =link_to root_path do
      = image_tag("header/logo.svg")
  .single-main
    .purchase-box
      %p
        商品の削除が完了しました。
      .link_to_mypage
        = link_to "マイページへ", "/users/#{current_user.id}", class: "purchase-mypage-link"

.fotter-gray
  .fotter-gray__box
    %nav
      %ul
        %li
          = link_to "" do
            プライバシーポリシー
        %li
          = link_to "" do
            利用規約
        %li
          = link_to "" do
            特定商取引に関する表記

    = link_to "", class: "fotter-logo" do
      =image_tag("fotter/logo-gray.svg")
    %p.fotter__copyright © 2017 Mercari

app/views/items/edit.html.haml
.single-container
  .single-header
    %h1
    =link_to root_path do
      = image_tag("header/logo.svg")
  .single-main
    .sell-container
      .sell-container__inner
        = form_for (@item) do |f|
          .sell-container__inner__head
            %h2
              商品の情報を入力
          .sell-upload-box
            = f.label :image, "出品画像", {class: 'form-label'}
            %span.form-require
              必須
            %p
              画像をアップロードします。
            .sell-dropbox-container
              %label.image-uploader
                = f.file_field :image
                = f.hidden_field :image_cache
                .sell-upload-drop-box
                  %pre 画像をアップロード

          .sell-content
            .form-group-first
              = f.label :name, "商品名", {class: 'form-label'}
              %span.form-require
                必須
              %br
              = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "input-default"
            .form-group
              = f.label :description, "商品の説明", {class: 'form-label'}
              %span.form-require
                必須
              %br
              = f.text_area :description, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライドグレーで傷はありません。あわせやすいのでおすすめです。", class: "input-default", size: "100"
          .sell-content
            %H3.sell-sub-head
              商品の詳細
            .sell-form-box
              .form-group-first
                = f.label :category, "カテゴリー", {class: 'form-label'}
                %span.form-require
                  必須
                .select-wrap
                  = f.select :category, [["-----", "NULL"], ["レディース", "レディース"], ["メンズ", "メンズ"]], {}, { class: "select-default" }

              .form-group
                = f.label :state, "商品の状態", {class: 'form-label'}
                %span.form-require
                  必須
                .select-wrap
                  = f.select :state, [["-----", "NULL"], ["新品、未使用", "新品、未使用"], ["未使用に近い", "未使用に近い"], ["目立った傷や汚れはなし", "目立った傷や汚れはなし"], ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]], {}, { class: "select-default" }

          .sell-content
            %H3.sell-sub-head
              配送について
            .sell-form-box
              .form-group-first
                = f.label :postage, "配送料の負担", {class: 'form-label'}
                %span.form-require
                  必須
                .select-wrap
                  = f.select :postage, [["-----", "NULL"], ["着払い(購入者負担)", "着払い(購入者負担)"], ["送料込み(出品者負担)", "送料込み(出品者負担)"]], {}, { class: "select-default" }

              .form-group
                = f.label :region, "発送元の地域", {class: 'form-label'}
                %span.form-require
                  必須
                .select-wrap
                  = f.select :region, [["-----", "NULL"], ["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉", "千葉"]], {}, { class: "select-default" }

            .sell-form-box
              .form-group
                = f.label :shipping_date, "発送までの日数", {class: 'form-label'}
                %span.form-require
                  必須
                .select-wrap
                  = f.select :shipping_date, [["-----", "NULL"], ["1~2日で発送", "1~2日で発送"], ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"]], {}, { class: "select-default" }

          .sell-content
            %H3.sell-sub-head
              公開範囲
            .sell-form-box
              .form-group-first
                = f.label :release, "商品の公開範囲について", {class: 'form-label'}
                %span.form-require
                  必須
                .select-wrap
                  = f.select :release, [["全体公開", "全体公開"], ["限定公開", "限定公開"]], {}, { class: "select-default" }

          .sell-content
            %H3.sell-sub-head
              販売価格(300〜9,999,999)
            .sell-form-box
              %ul.l-left
                %li.form-group-first
                  = f.label :price, "価格", {class: 'form-label'}
                  %span.form-require
                    必須
              .input-price
                ¥
                = f.text_field :price, placeholder: "例)300", class: "input-price-area"

            .commision
              .l-left
                販売手数料 (10%)
              .l-right
                ー
            .profits
              .l-left
                販売利益
              .l-right
                ー
          .sell-content
            %p
              禁止されている出品、行為を必ずご確認ください。</br>
              またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            .form-group
              = f.submit "投稿する", class: "btn btn__red"
              = link_to "もどる", root_path, class: "btn btn__gray"

.fotter-gray
  .fotter-gray__box
    %nav
      %ul
        %li
          = link_to "" do
            プライバシーポリシー
        %li
          = link_to "" do
            利用規約
        %li
          = link_to "" do
            特定商取引に関する表記

    = link_to "", class: "fotter-logo" do
      =image_tag("fotter/logo-gray.svg")
    %p.fotter__copyright © 2017 Mercari

app/views/items/index.html.haml
.header-wrapper
= render "items/main/header"

.items
.pickup-contents-wrapper
.pickup-contents
  %h2.pickup-contents__title
    %p アイテム一覧 </br></br>
  %section.items-contents
    .items-box-content
      = render partial: 'item', collection: @items, as: :item

.bottom-dl-area-wrapper
= render "items/main/bottom-dl-area"
.fotter-wrapper
= render "items/main/fotter"

app/views/items/main/_bottom-dl-area.html.haml
.bottom-dl-area
  .bottom-dl-area__contents
    .left-img
      %h2
        スマホでかんたんフリマアプリ
      %p
        今すぐ無料ダウンロード！
      .app-banner-icon.clearfix
        %figure.app-banner-icon__icons-box
          = image_tag("bottom-dl-area/mercari_icon.png", class: "mercari-icon")
        %ul.imgs.clearfix
          %li
            = image_tag("bottom-dl-area/app-store.svg", class: "imgs__store app")
          %li
            = image_tag("bottom-dl-area/google-play.svg", class: "imgs__store google")
    .right-img
      = image_tag("bottom-dl-area/download_content_pc.png")

app/views/items/main/_fotter.html.haml
.fotter
  %nav
    %ul
      %li.fotter-cell.about-mercari
        %h2.fotter__header
          メルカリについて
        %ul
          %li
            = link_to "" do
              プライバシーポリシー
          %li
            = link_to "" do
              利用規約
          %li
            = link_to "" do
              会社概要（運営会社）
          %li
            = link_to "" do
              特定商取引に関する表記
          %li
            = link_to "" do
              法令遵守と犯罪防止のために
          %li
            = link_to "" do
              採用情報
          %li
            = link_to "" do
              メルカリアッテ

      %li.fotter-cell.look-at-mercari
        %h2.fotter__header
          メルカリを見る
        %ul
          %li
            = link_to "" do
              カテゴリー一覧
          %li
            = link_to "" do
              ブランド一覧
          %li
            = link_to "" do
              出品地域一覧
          %li
            = link_to "" do
              公式Twitter
          %li
            = link_to "" do
              公式Facebook

      %li.fotter-cell.help-and-guid
        %h2.fotter__header
          ヘルプ＆ガイド
        %ul
          %li
            = link_to "" do
              メルカリロゴ利用ガイドライン
          %li
            = link_to "" do
              お知らせ
          %li
            = link_to "" do
              らくらくメルカリ便とは
          %li
            = link_to "" do
              大型らくらくメルカリ便とは
          %li
            = link_to "" do
              車体取引ガイド
          %li
            = link_to "" do
              メルカリあんしん・あんぜん宣言！
      %li.fotter-cell.country
        %h2.fotter__header
          国
        %ul
          %li
            .us
              = link_to "" do
                =image_tag("fotter/flag_us.png")
                United States
          %li
            .uk
              = link_to "" do
                =image_tag("fotter/flag_uk.png")
                United Kingdom
          %li
            .jp
              = link_to "" do
                =image_tag("fotter/flag_jp.png")
                日本
  = link_to "", class: "fotter__icon" do
    =image_tag("fotter/logo-white.svg")
  %p.fotter__copyright © 2017 Mercari

.exhibit
  =link_to new_item_path, "data-turbolinks": false do
    .text
      出品
    %i.fa.fa-camera

app/views/items/main/_header.html.haml
.default-container
  %header
    .logo-and-search.clearfix
      =link_to root_path do
        = image_tag("header/logo.svg", class: "logo-and-search__logo left-float")
      .search
        %form.logo-and-search__search.right-float
          %input{value:"", placeholder:"キーワードから探す" }
          = link_to items_path do
            %i.fa.fa-search
    .lists.clearfix
      .lists__left.left-float
        %ul
          %li.categories
            %h2
              = link_to items_path do
                カテゴリー
          %li.brands
            %h2
              = link_to items_path do
                ブランド
      .signin-and-signup.right-float
        %ul.account
          - if user_signed_in?
            %li.signin-btn
              = link_to "マイページ", "/users/#{current_user.id}", class: "signin-btn__text"
          - else
            %li.signin-btn
              = link_to "ログイン", user_session_path, class: "signin-btn__text"
            %li.signup-btn
              = link_to "新規会員登録", new_user_registration_path, class: "signup-btn__text"
          %end

app/views/items/main/_main.html.haml
.banner
  = image_tag("main/banner.jpg", class: "banner__img")
.main-visual
  .main-visual__description
    .main-visual__description__left-content
      %h2
        スマホでかんたん</br>
        フリマアプリ
      %p
        メルカリはスマホカメラからすぐに出品できる<br/>
        購入時も安心な独自システムのアプリです
      .app-download.clearfix
        = image_tag("main/app-store.svg", class: "app-download__store app")
        = image_tag("main/google-play.svg", class: "app-download__store google")
    = image_tag("main/main_content_pc.png", class: "main-visual__description__right-content")

.introductions
  %h2
    メルカリは、かんたんに売り買いができて、<br/>
    あんしん・あんぜんなお取引ができる<br/>
    フリマアプリです。
  %ul
    %li.introduction
      %h3.introduction__title
        %span 1
        簡単に出品できる
      = image_tag("main/start1.jpg", class: "introduction__img")
      %p.introduction__description
        スマホで写真を撮って<br/>
        特徴を入力するだけで、<br/>
        簡単に出品できます
    %li.introduction
      %h3.introduction__title
        %span 2
        すぐに購入できる
      = image_tag("main/start2.jpg", class: "introduction__img")
      %p.introduction__description
        ボタン1つで即購入。<br/>
        あとは出品者からの発送を待つだけです。
    %li.introduction
      %h3.introduction__title
        %span 3
        商品がたくさん
      = image_tag("main/start3.jpg", class: "introduction__img")
      %p.introduction__description
        毎日数十万品以上の新商品が<br/>
        出品されるので、ほしいものがきっと見つかります。

.middle-dl-area
  .middle-dl-area__description
    %h2
      誰でも簡単に、売ったり買ったりを楽しめる
    %p
      メルカリには、<br/>ファッションから雑貨、家電、本や漫画に至るまで、<br/>幅広いジャンルの商品がたくさん。<br/>今はもう店頭に置いていない掘り出し物も見つかるかもしれません。<br/>早速アプリをダウンロードしてはじめよう！
    .app-download.clearfix
      = image_tag("main/app-store.svg", class: "app-download__store app")
      = image_tag("main/google-play.svg", class: "app-download__store google")

.features
  %h2.features__title
    メルカリの特徴
  .feature.clearfix
    %section.one
      %figure
        = image_tag("main/watch.svg")
      %h3
        3分でかんたん売り買い
      %p
        着なくなった服や小物、本などを売ってみよう！お小遣い稼ぎに使えます
    %section.two
      %figure
        = image_tag("main/lock.svg")
      %h3
        あんしんの売買システム
      %p
        お金のやりとりはメルカリが仲介し、商品が届いてから出品者に振り込まれるので安心です
    %section.three
      %figure
        = image_tag("main/card.svg")
      %h3
        多彩な支払い方法
      %p
        購入した商品のお支払いは、クレジットカード/キャリア決済/コンビニ/ATMからどうぞ！
    %section.four
      %figure
        = image_tag("main/free-jp.svg")
      %h3
        出品はもちろん無料
      %p
        その他、会員登録料・月会費・カード手数料は一切かかりません

app/views/items/main/_pickup-contents.html.haml
.pickup-contents
  %h2.pickup-contents__title
    ピックアップカテゴリー
  %section.items-contents.clearfix
    %h3.items-contents__title
      %a
        レディース
    .items-box-content.clearfix
      .items-box.one
        %a.detail-page
          = image_tag("pickup-contents/item1.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              話題 一粒ダイヤネックレスレディースピンクゴールド
            .item-price.clearfix
              ¥ 780
      .items-box.two
        %a.detail-page
          = image_tag("pickup-contents/item2.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              動きやすい！レディース 部屋着 ブラック L ・上下2点セット
            .item-price
              ¥ 1,280
      .items-box.three
        %a.detail-page
          = image_tag("pickup-contents/item3.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              クロス チョーカー
            .item-price
              ¥ 1,333
      .items-box.four
        %a.detail-page
          = image_tag("pickup-contents/item4.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              しまむら　トートバッグ　スウェット生地　2way　紺
            .item-price
              ¥ 1,500

.pickup-contents
  %h2.pickup-contents__title
    ピックアップブランド
  %section.items-contents.clearfix
    %h3.items-contents__title
      %a
        シャネル
    .items-box-content.clearfix
      .items-box.one
        %a.detail-page
          = image_tag("pickup-contents/brand1.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              CHANELスタンプ
            .item-price.clearfix
              ¥ 2,700
      .items-box.two
        %a.detail-page
          = image_tag("pickup-contents/brand2.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              CHANEL 534 エスパドリーユ
            .item-price
              ¥ 2,000
      .items-box.three
        %a.detail-page
          = image_tag("pickup-contents/brand3.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              シャネル ニュートラベルライン ショルダーバッグ グレー
            .item-price
              ¥ 16,000
      .items-box.four
        %a.detail-page
          = image_tag("pickup-contents/brand4.jpg", class: "detail-page__img")
          .detail-page__body
            %h3.item-name
              CHANEL シャネル サングラス イタリア製
            .item-price
              ¥ 12,000

app/views/items/saled.html.haml
.header-wrapper
= render "items/main/header"

.items
.pickup-contents-wrapper
.pickup-contents
  %h2.pickup-contents__title
    %p 出品した商品一覧 </br></br>
  %section.items-contents
    .items-box-content
      = render partial: 'item', collection: @items, as: :item

.bottom-dl-area-wrapper
= render "items/main/bottom-dl-area"
.fotter-wrapper
= render "items/main/fotter"

app/views/items/show.html.haml
.header-wrapper
= render "items/main/header"
.banner
  = image_tag("main/banner.jpg", class: "banner__img")

.item-detail
  .l-container
    .l-content
      .l-content__container
        %h2.item-detail-name
          = @item.name
        - if current_user.id == @item.saler_id
          .saler-box
            .edit-and-destroy
              = link_to '編集', edit_item_path(@item), method: :get
              = link_to '削除', item_path, method: :delete, data: {confirm: "本当に削除しますか？"}
            .url-copy
              %h1 この商品のURL:
              %textarea#fe_text.copy-url-input{:cols => "50", :name => "", :rows => "1"}
                = request.url
              %button#d_clip_button.my_clip_button{"data-clipboard-target" => "fe_text", "data-clipboard-text" => "Default clipboard text from attribute"}
                %b コピー
        %end

        .item-content
          .item-content__main-photo
            = image_tag @item.image
          - if @item.sold?
            .item-sold-out-badge
              SOLD
          %end
          .item-content__sub-photo
            = image_tag @item.image
          .item-content__sub-photo
            = image_tag @item.image
          .item-content__sub-photo
            = image_tag @item.image
          .item-content__sub-photo
            = image_tag @item.image
        %table.item-detail-table
          %tbody
            %tr
              %th
                出品者
              %td
                = link_to "#{@user.nickname}", ""
                .item-user-rating
                  %i.icon-good
                .item-user-rating
                  %i.icon-normal
                .item-user-rating
                  %i.icon-bad
            %tr
              %th
                カテゴリー
              %td
                = link_to "#{@item.category}", ""
            %tr
              %th
                商品の状態
              %td
                = @item.state
            %tr
              %th
                配送元地域
              %td
                = @item.region
            %tr
              %th
                配送の目安
              %td
                = @item.shipping_date
            %tr
              %th
                公開範囲
              %td
                = @item.release

      .item-detail-price
        %span.item-detail-price__bold
          ¥
          =@item.price.to_s(:delimited)
        %span.item-detail-price__shipping-fee
          送料込み
      - if @item.sold?
        .item-buy-btn__gray
          売り切れました
      - elsif current_user == @item.saler
        .item-buy-btn__gray
          あなたが出品した商品です。
      -else
        .item-buy-btn
          = form_tag("/items/#{@item.id}/purchase", action: :purchase, method: :post) do
            %script.payjp-button{"data-key" => Rails.application.secrets.payjp_secret_key, :src => "https://checkout.pay.jp", :type => "text/javascript"}
      %end

      .item-description
        %p
          = simple_format(@item.description)

      .item-button-container
        .item-button-left
          %button.item-button-like
            %i.icon-like-border
            %span
              いいね!
        .item-button-right
          .item-button-report
            = link_to "不適切な商品の報告", "", class: "item-button"

      .item-comment-container
        %ul.message-items
          = render partial: 'comment', collection: @comments, as: :comment
        - if current_user
          .comment-form
            = form_for @comment, :url => "/items/#{@item.id}/comments" do |f|
              = f.label :name, "相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。", {class: 'comment-form__notice'}
              %br
              = f.text_area :text, placeholder: "", class: "comment-form__input"
              = f.submit "コメントする", class: "btn btn__red"


    .l-side
      .l-visible-large
        = image_tag("items/side_banner.jpg")

.bottom-dl-area-wrapper
= render "items/main/bottom-dl-area"
.fotter-wrapper
= render "items/main/fotter"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/users/show.html.haml
.header-wrapper
= render "items/main/header"

.banner
  = image_tag("main/banner.jpg", class: "banner__img")
.mypage
  .mypage__nav-container
    .mypage-nav-list
      %nav.mypage-nav
        %ul
          %li
            %h1 あなたの売上金:
            %p
              ¥
              = current_user.wallet.to_s(:delimited)
          %li
            = link_to "商品を出品する", new_item_path, method: :get
          %li
            = link_to "商品を購入する", items_path, method: :get
          %li
            = link_to "出品した商品", saled_items_path, method: :get
          %li
            = link_to "購入した商品", bought_items_path, method: :get
          %li
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          %li
            = link_to "トップへ戻る", root_path, method: :get

.bottom-dl-area-wrapper
= render "items/main/bottom-dl-area"
.fotter-wrapper
= render "items/main/fotter"